Feature/homework 1
ArtyomSolovev/SHIFTHomeworks pull request #2
Opened 2021-10-29 21:04 UTC by ArtyomSolovev

В приложение с помощью command line tool можно создавать экземпляр структуры Car и просмотреть уже присутствующие автомобили в массиве. 
Соловьев Артем

2021-10-31 05:51 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/Body.swift
> +    case Sedan = "Седан", SUV = "Кроссовер", Coupe = "Купе", Van = "Фургон", Hatchback = "Хэтчбек", Pickup = "Пикап", none
Лучше одна строка - один case

2021-10-31 05:52 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +func getTypeOfBody(number:Int) -> Body{
место этого метода внутри enum-а

2021-10-31 05:53 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +var x: Int?
название переменной не говорит ни о чём

2021-10-31 05:54 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +print("""
глобальный print - список команд выведется только в начале работы (может это - фича, но не удобно в работе)

2021-10-31 05:55 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +        print("Введите производтеля")
- [ ] логику каждого case вынести в отдельные методы

2021-10-31 05:56 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +var x: Int?
- [ ] переименовать

2021-10-31 05:56 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +func getTypeOfBody(number:Int) -> Body{
- [ ] перенести

2021-10-31 06:00 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +        let body = getTypeOfBody(number: Int(readLine() ?? "1")!)
если при неправильном вводе кузова (readLine) подставляем "1 - седан" (что довольно странно), то зачем используется форс-анврап, а не подставляется 1 при nil ?

2021-10-31 06:01 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +        cars.append(Car(manufacturer: manufacturer!, model: model!, body: body, yearOfIssue: yearOfIssue, carNumber: carNumber))
- [ ] избавься от форс-анврапов (во ВСЁМ приложении)

2021-10-31 06:02 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +repeat{
не работай глобально, оберни в какой-нить метод (хотя бы run() ) и только его глобально дёрни

2021-10-31 06:04 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +        print("Выберите машины с каким типом кузова хотите увидеть: 1)Седан 2)Кроссовер 3)Купе 4)Фургон 5)Хэтчбек 6)Пикап")
заиспользуй для этого enum.allCases (поддержи CaseIterable и заиспользую enumerated)

2021-10-31 06:05 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +        let body = getTypeOfBody(number: Int(readLine() ?? "1")!)
Тут копи-паста и то же самое замечание.

2021-10-31 06:07 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +            if car.body == body{
- [ ] очень похоже, что здесь должен быть filter

2021-10-31 06:10 UTC, AlexRaptor approved these changes
Как я понял, этот ПР только для gitignore ?

2021-10-31 06:15 UTC, AlexRaptor requested changes
Проведи, плиз, рефакторинг (я в замечаниях указал, что нужно сделать - поделить на методы, переупорядочить, подправить именование)
Ещё:

- [ ] убери DS_Store из репы
- [ ] дополни README в ветке

Название проекта не по требованиям, но это ладно - мы сами накосячили, забыв поправить его в ТЗ :)

2021-10-31 21:28 UTC, ArtyomSolovev commented
> Проведи, плиз, рефакторинг (я в замечаниях указал, что нужно сделать - поделить на методы, переупорядочить, подправить именование) Ещё:
> 
> * [ ]  убери DS_Store из репы
> * [ ]  дополни README в ветке
> 
> Название проекта не по требованиям, но это ладно - мы сами накосячили, забыв поправить его в ТЗ :)

У меня вроде DS_Store и так нету, а чем дополнять README?

2021-11-01 15:32 UTC, AlexRaptor requested changes
Стало намного лучше.
Поправь замечания и удали DS_Store из репозитория.
Как-то так:
git rm --cached file1.txt
git commit -m "remove file1.txt"

2021-11-01 15:32 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/Body.swift
> +    case Unknown = "Некатегорированный"
- [ ] `case` принято называть с маленькой буквы, как переменные

2021-11-01 15:32 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +func showAuto2(){
"2" - это номер автомобиля, что нужно показать, или это 2 раза нужно его показать?

- [ ] переименуй, что бы было понятно, что этот метод делает

2021-11-01 15:32 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +func showAuto(){
- [ ] ну и множественное число: или autoS или carS
и следующий метод аналогично

2021-11-01 15:32 UTC, AlexRaptor commented on CarsWeekOne/CarsWeekOne/main.swift
> +    let body = Body.Unknown.getTypeOfBody(number: Int(readLine() ?? "0") ?? 0)
Нет!!!

- [ ] сделай метод статическим и будет  `Body.getType...`

2021-11-02 03:33 UTC, AlexRaptor approved these changes
Можно мержить

2021-11-02 05:16 UTC, merged