Feature/homework 3
ArtyomSolovev/SHIFTHomeworks pull request #5
Opened 2021-11-15 09:29 UTC by ArtyomSolovev

2021-11-15 15:01 UTC, c0dedbear requested changes
Анимации прикольные.

Смотри комменты, в целом все неплохо.

2021-11-15 15:01 UTC, c0dedbear commented on VisitCard/VisitCard/Constants.swift
> +    enum aboutMe : String{
вложенные структуры должны также с Большой буквы начинаться.

2021-11-15 15:01 UTC, c0dedbear commented on VisitCard/VisitCard/Constants.swift
> +enum Conatants {
наверное Constants?

2021-11-15 15:01 UTC, c0dedbear commented on VisitCard/VisitCard/Constants.swift
> +import Foundation
импорт лишний

2021-11-15 15:01 UTC, c0dedbear commented on VisitCard/VisitCard/ThirdViewController.swift
> +    @objc private func buttonActionOne(sender: UIButton!) {
мне кажется что я первый раз такое встречаю, что в сигнатуре метода опционал через ! указывается)
Вообщем даже если оно так работает не надо так делать.
Например у нас в приложении форсанрапы на уровне линта депрекейтятся.

2021-11-15 15:01 UTC, c0dedbear commented on VisitCard/VisitCard/Constants.swift
> +        case briefInformation = "Соловеьв Артем, 22 года"
Тут ошибочка в фамилии)

2021-11-15 15:05 UTC, c0dedbear commented
Так а еще у тебя проект называется не по ТЗ. Должен называться myCV. Открывай Гугл и смотри как переименовать проект и не сломать его)

2021-11-16 05:05 UTC, c0dedbear requested changes
В папке с проектом остался VisitCard.xcodeproj

2021-11-16 09:29 UTC, c0dedbear commented
<img width="900" alt="Screenshot 2021-11-16 at 12 26 32" src="https://user-images.githubusercontent.com/21219011/141958998-9aacfb88-4be7-4942-afb9-612316edf2b4.png">
VisitCard остался

2021-11-16 10:09 UTC, ArtyomSolovev commented
> <img alt="Screenshot 2021-11-16 at 12 26 32" width="900" src="https://user-images.githubusercontent.com/21219011/141958998-9aacfb88-4be7-4942-afb9-612316edf2b4.png">
> 
> VisitCard все еще лежит

<img width="982" alt="image" src="https://user-images.githubusercontent.com/80806951/141965391-52b11633-89d6-4bfe-976a-31a9a2bdf120.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/80806951/141965417-e2a48974-3e8b-4019-96d6-ad24b7b97ea2.png">
У меня ни в гите, ни на своем маке вообще нет этой папки, я не представляю, как её можно удалить

2021-11-16 10:15 UTC, c0dedbear commented
> > <img alt="Screenshot 2021-11-16 at 12 26 32" width="900" src="https://user-images.githubusercontent.com/21219011/141958998-9aacfb88-4be7-4942-afb9-612316edf2b4.png">
> > VisitCard все еще лежит
> 
> <img alt="image" width="982" src="https://user-images.githubusercontent.com/80806951/141965391-52b11633-89d6-4bfe-976a-31a9a2bdf120.png">
> 
> <img alt="image" width="954" src="https://user-images.githubusercontent.com/80806951/141965417-e2a48974-3e8b-4019-96d6-ad24b7b97ea2.png">
> 
> У меня ни в гите, ни на своем маке вообще нет этой папки, я не представляю, как её можно удалить

ммм. видимо у меня после pull не обновилось.

2021-11-16 10:15 UTC, c0dedbear commented
Принято

2021-11-16 10:15 UTC, merged